name: Update Docker Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version tag
      id: extract_version
      run: echo "::set-output name=VERSION_TAG::${GITHUB_REF#refs/tags/}"

    - name: Build and push Docker image
      run: |
        VERSION_TAG=${{ steps.extract_version.outputs.VERSION_TAG }}
        docker build -t shivkumar/github-action:${VERSION_TAG} .
        docker push shivkumar/github-action:${VERSION_TAG}
        docker tag shivkumar/github-action:${VERSION_TAG} shivkumar/github-action:latest
        docker push shivkumar/github-action:latest

    - name: Increment version
      id: increment_version
      run: |
        VERSION=${{ steps.extract_version.outputs.VERSION_TAG }}
        IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
        PATCH_VERSION=$((VERSION_PARTS[2] + 1))
        NEW_VERSION="${VERSION_PARTS[0]}.${VERSION_PARTS[1]}.$PATCH_VERSION"
        echo "::set-output name=NEW_VERSION::$NEW_VERSION"

    - name: Create new tag
      run: |
        NEW_VERSION=${{ steps.increment_version.outputs.NEW_VERSION }}
        git tag $NEW_VERSION
        git push origin $NEW_VERSION
