name: 'Build and Push Docker Image'

on:
  workflow_dispatch:
    inputs:
      docker_username:
        description: 'Docker Hub Username'
        required: true
      docker_password:
        description: 'Docker Hub Password'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ github.event.inputs.docker_username }}
          password: ${{ github.event.inputs.docker_password }}

      - name: Make build-and-push.sh executable
        run: chmod +x ./build-and-push.sh

      - name: Run build and push script
        run: ./build-and-push.sh
